package com.golem.app.collection.ticket;

import com.golem.app.collection.ConsoleRead;
import com.golem.app.collection.TicketCollection;

import java.time.LocalDate;

/**
 * Ticket element is main data object for this collection
 */

public class Ticket implements Comparable <Ticket>, ConsoleRead {
    /**
     * unique id.
     * -not null
     * -autogenerated
     * -greater than 0
     */
    private int id;

    private String ticketKey;
    /**
     * Ticket name
     * -not null @see
     * -not empty @see
     */
    private String name = "";

    /**
     * ticket venue
     * -can be null
     */
    private Venue venue;

    /**
     * coordinates
     * -not null
     */
    private Coordinates coordinates;

    /**
     * Ticket type
     * -not null
     */
    private TicketType type;

    /**
     * Creation date
     * -not null
     * -autogenerated
     */
    private LocalDate creationDate;

    /**
     * Ticket price
     * -not null
     * -greater than 0
     */
    private Double price;

    /**
     * ticket comment
     * -can be null
     */
    private String comment;

    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getPrice() {
        return price;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getComment() {
        return comment;
    }

    public void setCreationDate(LocalDate creationDate) {
        this.creationDate = creationDate;
    }
    public LocalDate getCreationDate() {
        return creationDate;
    }

    public void setCoordinates(Coordinates coordinates) {
        this.coordinates = coordinates;
    }
    public Coordinates getCoordinates() {
        return coordinates;
    }

    public void setType(TicketType type) {
        this.type = type;
    }
    public TicketType getType() {
        return type;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }

    public void setVenue (Venue venue) {
        this.venue = venue;
    }
    public Venue getVenue() {
        return venue;
    }

    public void setId(int id) {
        this.id = id;
    }
    public int getId() {
        return id;
    }

    {
        coordinates = new Coordinates();
        venue = new Venue();
    }

    /**
     * default constructor. Just init object.
     */
    public Ticket () {}

    /**
     * implemented and overrided compareTo method.
     * @param o ticket to be compared.
     * @return int
     * -less than 0 -> o less than object
     * -equal to 0 -> 0 equal to object (due id generation - imposable)
     * -greater than 0 -> greater than object
     */
    @Override
    public int compareTo(Ticket o) {
        int compare;
        if ((compare = getName().compareTo(o.getName())) != 0) return compare;
        if ((compare = getCoordinates().compareTo(o.getCoordinates())) != 0) return compare;
        if ((compare = getPrice().compareTo(o.getPrice())) != 0) return compare;
        if ((compare = getComment().compareTo(o.getComment())) != 0) return compare;
        if ((compare = getType().compareTo(o.getType())) != 0) return compare;
        if (this.getVenue() != null && o.getVenue() == null) return 1;
        if (this.getVenue() == null && o.getVenue() != null) return -1;
        if ((compare = getVenue().compareTo(o.getVenue())) != 0) return compare;
        if ((compare = getCreationDate().compareTo(o.getCreationDate())) != 0) return compare;
        return o.getId() - getId();
    }

    /**
     * form string to console output. Comfortable for user reading.
     * @return String
     */
    @Override
    public String toReadString() {
        String tempVenue = "";
        if (venue != null) {
            tempVenue += "\n";
            tempVenue += venue.toReadString();
        }
        return "Ticket >>\n" +
                "   id: " + id + "\n" +
                "   name: " + name + "\n" +
                "   creationDate: " + creationDate + "\n" +
                "   price: " + price + "\n" +
                "   comment: " + comment + "\n" +
                "   type: " + type.toString() + "\n" +
                coordinates.toReadString() +
                tempVenue;
    }

    /**
     * enum for ticket type. Used generally in pair with ticket.
     */
    public enum TicketType {
        VIP,
        USUAL,
        BUDGETARY,
        CHEAP
    }

}